---
- name: Configure Kubernetes
  script: k8s-cfg.sh

- name: Configure Kubernetes master-node
  script: master-conf.sh

- name: Copy argo-cd values.yml file to the target machine
  copy:
    src: values.yml
    dest: /tmp/values.yml

- name: Install Helm package manager
  script: helm-install.sh

#- name: Add a helm repository with cli
#  command: 
#  cmd: helm repo add argo https://argoproj.github.io/argo-helm

- name: Add a helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Helm update
  command: helm repo update

- name: Install argo-cd chart
  command:
    cmd: helm install argocd -n argocd --create-namespace argo/argo-cd --version 3.35.4 -f /tmp/values.yml

- name: Fetch token-file from first vm to local
  fetch:
    src: "{{ dest_path }}token.sh"
    dest: /tmp/fetched
    flat: yes

