---
- name: Copy files on remote server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: argo-app.yml, dest: "{{ objects_path }}" }
    - { src: argocd-cli.sh, dest: "{{ objects_path }}" }

- name: Create Argo application and install Argo CLI
  shell:
    chdir: "{{ objects_path }}"
    cmd: |
      kubectl apply -f .
      bash argocd-cli.sh
