---
- name: Configure Kubernetes worker-node
  script: k8s-cfg.sh

- name: Copy token-file from local to second vm
  copy:
    src: /tmp/fetched
    dest: "{{ dest_path }}token.sh"

- name: Join worker node to master
  command: bash ./token.sh
  become: true
  become_method: sudo

