---
###
- name: First vm section      
  hosts: azure-vm-1

  collections:
  - kubernetes.core  

  roles:
    - role: master_node_config

###      
- name: Second vm section
  hosts: azure-vm-2

  roles:
    - role: worker_node_config

###
- name: Create argocd application
  hosts: azure-vm-1

  roles:
    - role: access_to_argo_app

###
- name: Add public-ip to API Server in master node
  hosts: azure-vm-1

  roles:
    - role: update_apiserver  

###
- name: Establish local kubectl connection to remote cluster
  hosts: localhost

  roles:
    - role: kubectl_on_local  

