---
###
- name: First vm section      
  hosts: azure-vm-1

  collections:
  - kubernetes.core  

  roles:
    - role: master_node_config

###      
- name: Second vm section
  hosts: azure-vm-2

  roles:
    - role: worker_node_config

###
- name: Final action
  hosts: azure-vm-1

  roles:
    - role: access_to_argo_app

